# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('animal', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('friendly', models.IntegerField()),
                ('desc', models.TextField()),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pets',
            name='adoped_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_animal', to='app_name.Users'),
        ),
        migrations.AddField(
            model_name='pets',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_animals', to='app_name.Users'),
        ),
    ]
