# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='adoped_by',
        ),
    ]
