# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-29 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app_name.Pets'),
            preserve_default=False,
        ),
    ]
